export const environment = {
  production: true,
  sessionInfoUrl: '/api/session',
  loginUrl: '/api/session/admin',
  userApiUrl: '/api/users',
  bookingApiUrl: '/api/bookings',
  bookingUserApiUrl: '/api/bookings/user',
  bookingGuestApiUrl: '/api/bookings/guest',
  flightApiUrl: '/api/flights',
  passengerApiUrl: '/api/passengers',
  // sessionInfoUrl: 'http://utopiaALB-464822832.us-east-1.elb.amazonaws.com:8081/api/session',
  // loginUrl: 'http://utopiaALB-464822832.us-east-1.elb.amazonaws.com:8081/api/session/admin',
  // userApiUrl: 'http://utopiaALB-464822832.us-east-1.elb.amazonaws.com:8081/api/users',
  // bookingApiUrl: 'http://utopiaALB-464822832.us-east-1.elb.amazonaws.com:3000/api/bookings',
  // flightApiUrl: 'http://utopiaALB-464822832.us-east-1.elb.amazonaws.com:3001/api/flights',
  // passengerApiUrl: 'http://utopiaALB-464822832.us-east-1.elb.amazonaws.com:3000/api/passengers',
};
